In [118]:
import geopandas as gpd
import pandas as pd
import numpy as np

shp = gpd.read_file(f"annots/Deir/Damage_Sites_Deir_ez_Zor_CDA.shp")
shp.head(6).T

,0,1,2,3,4,5
SiteID,Building (General / Default),Building (General / Default),Building (General / Default),Building (General / Default),Building (General / Default),Building (General / Default)
SensDt,2013-10-24,2013-10-24,2013-10-24,2013-10-24,2013-10-24,2013-10-24
SensorID,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades
ConfID,Medium,Medium,Medium,Uncertain,Very High,Very High
DaSitCl,Destroyed,Destroyed,Moderate Damage,Moderate Damage,Destroyed,Severe Damage
SensorDate,2014-05-13,2014-05-13,2014-05-13,2014-05-13,2014-05-13,2014-05-13
SensID2,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades
ConfID2,Medium,Medium,Medium,Medium,Very High,Very High
DaSitCl2,Destroyed,Destroyed,Moderate Damage,No Visible Damage,Destroyed,Severe Damage
Damst2,No change,No change,No change,Decrease - damage,No change,No change
SensDt3,2015-05-10,2015-05-10,2015-05-10,2015-05-10,2015-05-10,2015-05-10
SensID3,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades,Pleiades
ConfId3,Medium,Medium,Medium,Medium,Very High,Very High
DaSitCl3,Destroyed,Destroyed,Moderate Damage,No Visible Damage,Destroyed,Severe Damage
Damst3,No change,No change,No change,No change,No change,No change
SensDt4,2016-05-25,2016-05-25,2016-05-25,2016-05-25,2016-05-25,2016-05-25
SensID4,Worldview-2,Worldview-2,Worldview-2,Worldview-2,Worldview-2,Worldview-2
ConfId4,Medium,Medium,Uncertain,Medium,Very High,Medium
DaSitCl4,Destroyed,No Visible Damage,Moderate Damage,No Visible Damage,Destroyed,Moderate Damage
Damst4,No change,Decrease - damage,No change,No change,No change,Decrease - damage
SensDt5,2017-11-09,2017-11-09,2017-11-09,2017-11-09,2017-11-09,2017-11-09
SensId5,Worldview-2,Worldview-2,Worldview-2,Worldview-2,Worldview-2,Worldview-2
ConfId5,Medium,Medium,Uncertain,Medium,Very High,Medium
DaSitCl5,Destroyed,No Visible Damage,Moderate Damage,No Visible Damage,Destroyed,Moderate Damage
Damst5,No change,No change,No change,No change,No change,No change
GrDaCl,Damaged Buildings,Damaged Buildings,Damaged Buildings,Damaged Buildings,Damaged Buildings,Damaged Buildings
FieldVl,Not yet field validated,Not yet field validated,Not yet field validated,Not yet field validated,Not yet field validated,Not yet field validated
Notes,None,None,None,None,None,None
Name,Deir ez Zor,Deir ez Zor,Deir ez Zor,Deir ez Zor,Deir ez Zor,Deir ez Zor
Neigh,Al Jami Al Kabeer wa Al Wasat,Qosour,Qosour,Qosour,Shuhuda,Shuhuda
Code,CE20130604SYR,CE20130604SYR,CE20130604SYR,CE20130604SYR,CE20130604SYR,CE20130604SYR
geometry,POINT (40.13379023600004 35.34347458600007),POINT (40.13146683000008 35.34175611100005),POINT (40.129801231000044 35.342157987000064),POINT (40.12923383200007 35.342266804000076),POINT (40.13174304200004 35.33071508900008),POINT (40.13187903700003 35.330865311000025)

In [119]:
shp['SensDt2'] = shp['SensorDate']

In [120]:
dcols = sorted([c for c in shp.columns if "SensDt" in c ])
icols = sorted([c for c in shp.columns if "DaSitCl" in c])
shp = shp[[*dcols, *icols, 'geometry']]
dcols, icols

(['SensDt', 'SensDt2', 'SensDt3', 'SensDt4', 'SensDt5'],
 ['DaSitCl', 'DaSitCl2', 'DaSitCl3', 'DaSitCl4', 'DaSitCl5'])

In [121]:
df = []
for k, row in shp.iterrows():
    entry = dict()
    for i in range(len(dcols)):
        if (row[dcols[i]] is not None):
            entry[row[dcols[i]]] = row[icols[i]]
    entry['geometry'] = row['geometry']
    df.append(entry)
newAnnots = gpd.GeoDataFrame(df)

mapping = {'Destroyed': 3, 'Severe Damage': 2, 'Moderate Damage': 1, 'No Visible Damage': 0, 'Impact Crater (Damage to Road)': np.nan, 'Impact Crater (Damage to Field)': np.nan }
for col in newAnnots.drop('geometry', axis=1).columns:
#     print(newAnnots[col].unique())
    newAnnots[col] = newAnnots[col].map(mapping)

newAnnots.to_file("deir-ez-zor_damage.gpkg")

In [163]:
city = 'raqqa'

In [164]:
shp = gpd.read_file(f"{city}_damage.gpkg")
shp.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 13160 entries, 0 to 13159
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   2013-10-22  340 non-null    float64
 1   2014-02-12  464 non-null    float64
 2   2015-05-29  1568 non-null   float64
 3   2017-02-03  1818 non-null   float64
 4   2017-10-21  12898 non-null  float64
 5   geometry    13160 non-null  geometry
dtypes: float64(5), geometry(1)
memory usage: 617.0 KB

In [165]:
shp.drop('geometry', axis=1).T

,0,1,2,3,4,5,6,7,8,9,...,13150,13151,13152,13153,13154,13155,13156,13157,13158,13159
2013-10-22,3.0,3.0,3.0,1.0,3.0,3.0,3.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-02-12,3.0,3.0,3.0,1.0,3.0,3.0,3.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-05-29,3.0,3.0,3.0,0.0,3.0,3.0,3.0,0.0,0.0,2.0,...,NaN,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-03,3.0,3.0,3.0,0.0,3.0,3.0,3.0,0.0,0.0,2.0,...,NaN,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN
2017-10-21,3.0,3.0,3.0,0.0,3.0,3.0,3.0,0.0,0.0,2.0,...,1.0,3.0,3.0,3.0,2.0,3.0,1.0,1.0,1.0,3.0

In [166]:
shp_o = gpd.read_file(f"{city}_damage_old.gpkg")
shp.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 13160 entries, 0 to 13159
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   2013-10-22  340 non-null    float64
 1   2014-02-12  464 non-null    float64
 2   2015-05-29  1568 non-null   float64
 3   2017-02-03  1818 non-null   float64
 4   2017-10-21  12898 non-null  float64
 5   geometry    13160 non-null  geometry
dtypes: float64(5), geometry(1)
memory usage: 617.0 KB

In [167]:
shp_o.drop('geometry', axis=1).T

,0,1,2,3,4,5,6,7,8,9,...,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695
2013-10-22,3,3,3,1,3,3,3,2,2,2,...,0,0,0,0,0,0,0,0,0,0
2014-02-12,3,3,3,1,3,3,3,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2015-05-29,3,3,3,0,3,3,3,0,0,2,...,3,3,3,3,3,3,3,3,1,1

In [168]:
newAnnot = gpd.sjoin(shp, shp_o.drop([c for c in shp_o.columns if 'geometry' not in c], axis=1), how='right').drop('index_left', axis=1)
newAnnot

,2013-10-22,2014-02-12,2015-05-29,2017-02-03,2017-10-21,geometry
0,3.0,3.0,3.0,3.0,3.0,POINT (38.99105 35.96747)
1,3.0,3.0,3.0,3.0,3.0,POINT (38.99105 35.96743)
2,3.0,3.0,3.0,3.0,3.0,POINT (38.99107 35.96731)
3,NaN,NaN,NaN,NaN,NaN,POINT (38.99098 35.96742)
4,3.0,3.0,3.0,3.0,3.0,POINT (38.99126 35.96763)
...,...,...,...,...,...,...
1691,NaN,NaN,3.0,3.0,3.0,POINT (38.98180 35.96075)
1692,NaN,NaN,3.0,3.0,3.0,POINT (38.98160 35.96101)
1693,NaN,NaN,NaN,NaN,NaN,POINT (38.98171 35.96083)
1694,NaN,NaN,1.0,1.0,1.0,POINT (39.01727 35.94674)
1695,NaN,NaN,1.0,1.0,1.0,POINT (39.01610 35.94576)

In [169]:
newAnnot.to_file(f"{city}_damage_new.gpkg", driver = 'GPKG')